services:
#    hk_platform.example:
#        class: HK\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     hk_platform.antispam:
         class: HK\PlatformBundle\Antispam\HKAntispam
